<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
        <script src="js/vendor/modernizr-2.6.2.min.js"></script>
		<!-- frank added -->
		<script src="js/vendor/jquery-1.10.2.min.js"></script>
	  	<script src="js/jquery.sliderTabs.js"></script>
		<script>
		$(function() {
		$("#mySliderTabs").sliderTabs();
	});
	</script>
		
		<!-- end frank added -->
		
		<link rel="stylesheet" href="css/styles/jquery.sliderTabs.css">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
		<section id="plan" class="two">
		<div class="container">
		<div id="mySliderTabs">
	        <ul>
	          <li><a href="#theOffice">The Office</a></li>
	          <li><a href="#parks">Parks and Recreation</a></li>
	          <li><a href="#southPark">South Park</a></li>
	        </ul>
	        <div id="theOffice">
	          <h3>Info about The Office</h3>
	          <p>Aoapsinasof asghais fnasof ws9ufh isujn asiufhasiufasdf aoisufd asfdhasifd usdhf saiudfh</p>
	          <p>Aoapsinasof asghais fnasof ws9ufh isujn asiufhasiufasdf aoisufd asfdhasifd usdhf saiudfh</p>
	          <p>Aoapsinasof asghais fnasof ws9ufh isujn asiufhasiufasdf aoisufd asfdhasifd usdhf saiudfh</p>
	        </div>
	        <div id="parks">
	          <h3>Info about Parks and Recreation</h3>
	          <p>Aoapsinasof asghais fnasof ws9ufh isujn asiufhasiufasdf aoisufd asfdhasifd usdhf saiudfh</p>
	        </div>
	        <div id="southPark">
	          <h3>Info about South Park</h3>
	          <p>Aoapsinasof asghais fnasof ws9ufh isujn asiufhasiufasdf aoisufd asfdhasifd usdhf saiudfh</p>
	        </div>
	    </div>
	</div>
</section>

        
    </body>
</html>
